version: '3'

services:
#  testserver:
#    image: testserver
#    ports:
#      - "55551:55551"
  nifireg:
    image: apache/nifi-registry
    ports:
      - "18080:18080"
  nifi:
    image: apache/nifi
    ports: 
      - "8443:8443"
      - "8080:8080"
    environment:
      ENTITY_TYPES: Medication,Patient
      AT_CONTEXT: https://fiware.github.io/data-models/context.jsonld
      NGSILD_HOST: http://scorpio:9090
      NOTIFICATION_PATH: notify
      NOTIFICATION_PORT: 4444
      NOTIFICATION_HOST: http://nifi
      HL7_HOST: http://testserver:55551
      TEMP_INTERVAL: 20
      NIFI_REG: http://nifireg:18080
      MY_HOST: http://nifi:8080
      ########## JVM ##########
      
      # -Xms
      #   The initial JVM heap size.
      #NIFI_JVM_HEAP_INIT: 512m

      # -Xmx
      #   The maximum JVM heap size.
      #NIFI_JVM_HEAP_MAX: 512m
      
      # -Xdebug
      #   The JVM Debugger can be enabled by setting this environment variable to any value.
      #NIFI_JVM_DEBUGGER: ''



      ########## Web ##########

      # nifi.web.http.host
      NIFI_WEB_HTTP_HOST: '0.0.0.0'
      
      # nifi.web.http.port
      #   HTTP Port
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - ./NGSILDHL7Flow.json:/home/nifi/NGSILDHL7Flow.json
      - ./loadtemplate.sh:/home/nifi/loadtemplate.sh
      - ./download:/home/nifi/download
    entrypoint: ["bash", "/home/nifi/loadtemplate.sh"]
  zookeeper:
    image: zookeeper
    ports:
      - "2181"
    logging:
      driver: none
  kafka:
    image: bitnami/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
#    logging:
#      driver: none
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    logging:
      driver: none
#    volumes:
#      - /var/lib/docker/volumes/b089a32ad3162e1f7152fe9a87bdb10f4340f02372ae802c65ea870ccefb863f/_data:/var/lib/postgresql/data
  scorpio:
#    image: scorpiobroker/scorpio:scorpio-aaio-no-eureka_1.1.0-SNAPSHOT
    image: scorpiobroker/all-in-one-runner:java-kafka-3.0.11
    ports:
      - "9090:9090"
#    environment:
#      SPRING_SECURITY_MODE: deactivated
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWT-SET-URI: http://localhost:1234/realms/scorpio/protocol/openid-connect/certs
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://localhost:1234/realms/scorpio
    depends_on:
      - postgres
      - kafka
